from tkinter import*
root=Tk()

Label(text="esmaspäev:").grid(row=0,column=0)
Label(text="teisipäev:").grid(row=1,column=0)
Label(text="kolmapäev:").grid(row=2,column=0)
Label(text="neljapäev:").grid(row=3,column=0)
Label(text="reede:").grid(row=4,column=0)

Button(text="tuge_est2:").grid(row=0,column=1)
Button(text="logistika:").grid(row=0,column=2,columnspan=2)
Button(text="matemaatika:").grid(row=0,column=3,columnspan=2)
Button(text=" ").grid(row=0,column=4,)
Button(text="keel:").grid(row=0,column=5,columnspan=2)
Button(text="tuge_matem:").grid(row=0,column=6)

Button(text="tuge_keemia:").grid(row=1,column=1)
Button(text="programeerimine:").grid(row=1,column=2,columnspan=3)
Button(text=" ").grid(row=0,column=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
Button(text="tuge_est2:").grid(row=0,rowspan=2,column=2,columnspan=2)
root.mainloop()
